version: "3"
services:
  namenode:
    image: dubachphil/hadoop_namenode
    volumes:
      - namenode:/hadoop/dfs/name
    ports:
      - 9870:9870
      - 8020:8020
      - 14000:14000
    env_file:
      - ./hadoop.env

  datanode1:
    image: dubachphil/hadoop_datanode
    volumes:
      - datanode1:/hadoop/dfs/data
    env_file:
      - ./hadoop.env

  datanode2:
    image: dubachphil/hadoop_datanode
    volumes:
      - datanode2:/hadoop/dfs/data
    env_file:
      - ./hadoop.env

  datanode3:
    image: dubachphil/hadoop_datanode
    volumes:
      - datanode3:/hadoop/dfs/data
    env_file:
      - ./hadoop.env

#  resourcemanager:
#    image: dubachphil/hadoop_resourcemanager
#    ports:
#      - 8088:8088
#    depends_on:
#      - namenode
#      - datanode
#    env_file:
#      - ./hadoop.env

#  nodemanager:
#    image: dubachphil/hadoop_nodemanager
#    ports:
#      - 10100-10199:8042
#    depends_on:
#      - resourcemanager
#    env_file:
#      - ./hadoop.env
  
#  historyserver:
#    image: dubachphil/hadoop_historyserver
#    ports:
#      - 8188:8188
#    depends_on:
#      - nodemanager
#    env_file:
#      - ./hadoop.env

  spark-master:
    image: dubachphil/spark_master
    ports:
      - 8080:8080
      - 7077:7077
      - 6066:6066
    environment:
      - INIT_DAEMON_STEP=setup_spark
    env_file:
      - ./hadoop.env

  spark-worker:
    image: dubachphil/spark_worker
    depends_on:
      - spark-master
    env_file:
      - ./hadoop.env

  zeppelin:
    image: dubachphil/zeppelin
    ports:
      - 80:9999
    volumes:
      - zeppelin_notes:/opt/zeppelin/notebook
      - zeppelin_config:/opt/zeppelin/conf
    env_file:
      - ./hadoop.env

volumes:
  zeppelin_notes:
  zeppelin_config:
  namenode:
  datanode1:
  datanode2:
  datanode3:
  
